### ISSUE TITLE
Transifex "test.md"

### ISSUE THREAD

**Issue by Artoria2e5** [securityfirst/Umbrella_content#12]
Someone seems to have added a "test.md" on Transifex; the content looks like some sort of sample Markdown syntax. A pretty glaring problem is that "List of elements" is broken down into three strings, preventing the translation from working at all for languages that only have a word order for possessive voice like `x1 FOO x2 -> x2 of x1`.

**Comment by rorymbyrne** [comment]
@klaidliadon ?

**Comment by klaidliadon** [comment]
Sorry, that was a test. I'll delete it right away

**Comment by rorymbyrne** [comment]
Thanks for reporting @Artoria2e5. Issue now fixed.
