### ISSUE TITLE
NET::ERR_CERT_DATE_INVALID on https://secfirst.org/

### ISSUE THREAD

**Issue by ghost** [securityfirst/Umbrella_content#14]
Just wanted to leave a comment saying this repo is coming up with an invalid certificate.  
![image](https://user-images.githubusercontent.com/14261951/154822310-2f058b23-da0f-472f-9961-d3f667ecbb19.png)
[secfirst.txt](https://github.com/securityfirst/Umbrella_content/files/8103148/secfirst.txt)

**Comment by rorymbyrne** [comment]
Thanks this was fixed
